### ISSUE TITLE
text-embeddings-inference fails with error attempting to alloc NV_CONFIDENTIAL_COMPUTE object

### ISSUE THREAD

**Issue by thundergolfer** [google/gvisor#9608]
### Description

gVisor fails to run any of the [supported models](https://github.com/huggingface/text-embeddings-inference#supported-models) of Huggingface's `text-embeddings-inference`. 

From looking at [`cuda_ioctl_sniffer`](https://github.com/thundergolfer/cuda_ioctl_sniffer) output it looks like the issue is a error when attempting to allocate an object of hClass `NV_CONFIDENTIAL_COMPUTE`:

```
2023-10-30T18:42:48.256282Z  INFO text_embeddings_router: router/src/main.rs:251: Starting model backend
  1: 0 =   9(      /dev/nvidiactl) 0x900 NV_ESC_CARD_INFO
  2: 0 =   9(      /dev/nvidiactl) 0x 20 NV_ESC_RM_ALLOC hRoot: 0 hObjectParent: 0 hObjectNew: c1d00028 hClass: NV01_ROOT_CLIENT(41) pAllocParms: (nil) status: 0x0
  3: 0 =   9(      /dev/nvidiactl) 0x 20 NV_ESC_RM_CONTROL client: c1d00028 object: c1d00028 cmd:      101 NV0000_CTRL_CMD_SYSTEM_GET_BUILD_VERSION params: 0x7ede681f1990 0x28 flags: 0 status 0x0
  4: 0 =   9(      /dev/nvidiactl) 0x 10 NV_ESC_RM_FREE
  5: 0 =   9(      /dev/nvidiactl) 0x 48 NV_ESC_CHECK_VERSION_STR
  6: 0 =   9(      /dev/nvidiactl) 0x900 NV_ESC_CARD_INFO
  7: 0 =   9(      /dev/nvidiactl) 0x 20 NV_ESC_RM_ALLOC hRoot: 0 hObjectParent: 0 hObjectNew: c1d00029 hClass: NV01_ROOT_CLIENT(41) pAllocParms: (nil) status: 0x0
  8: 0 =   9(      /dev/nvidiactl) 0x 20 NV_ESC_RM_CONTROL client: c1d00029 object: c1d00029 cmd:      d04 NV0000_CTRL_CMD_CLIENT_SET_INHERITED_SHARE_POLICY params: 0x7ede681f1f04 0xc flags: 0 status 0x0
  9: 0 =   9(      /dev/nvidiactl) 0x 20 NV_ESC_RM_CONTROL client: c1d00029 object: c1d00029 cmd:      d04 NV0000_CTRL_CMD_CLIENT_SET_INHERITED_SHARE_POLICY params: 0x7ede681f1f04 0xc flags: 0 status 0x0
 10: -1 =   9(      /dev/nvidiactl) 0x 28 NV_ESC_RM_ALLOC hRoot: c1d00029 hObjectParent: c1d00029 hObjectNew: 5c000001 hClass: NV_CONFIDENTIAL_COMPUTE(cb33) pAllocParms: 0x7ede681f1f1c status: 0x0
       0: 29 00 D0 C1 00 00 00 00 00 00 00 00 93 D5 61 92
      10: D3 7E 00 00 01 00 00 00 0D 02 00 00 3C 00 00 00
      20: 88 67 EA 01 C0 1F 1F 68 DE 7E 00 00 00 00 00 00
      30: 00 00 00 00 01 00 00 00 00 00 00 00 65 2C 44 92
 11: 0 =   9(      /dev/nvidiactl) 0x 10 NV_ESC_RM_FREE
thread 'main' panicked at /root/.cargo/git/checkouts/cudarc-a08d71fd9258e74e/8be6ff4/src/driver/safe/core.rs:51:24:
called `Result::unwrap()` on an `Err` value: DriverError(CUDA_ERROR_OPERATING_SYSTEM, "OS call failed or operation not supported on this OS")
```

Given this, the fix may already be in the works: https://github.com/google/gvisor/commit/d687b573d680fb42d9349c0d6cae6282c9d6c0e6. But in case https://github.com/google/gvisor/issues/9593 and this error are actually different I've created this tracking issue.

### Steps to reproduce

These reproduction steps were run on a custom AWS AMI running Oracle Linux. The GPU is a T4:

```
Mon Oct 30 19:04:15 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.60.13    Driver Version: 525.60.13    CUDA Version: 12.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:1E.0 Off |                 ERR! |
| N/A   24C    P8     9W /  70W |      2MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

But I can get the same error result using an A10G result.

**1. Install gvisor**

```bash
ARCH="x86_64"  # all workers are x86
URL="https://storage.googleapis.com/gvisor/releases/master/latest/${ARCH}"
wget -nc "${URL}/runsc" "${URL}/runsc.sha512"
chmod +x runsc
sudo cp runsc /usr/local/bin/runsc
sudo /usr/local/bin/runsc install
sudo systemctl reload docker
```

**2. Add GPU enabling gvisor options**

In `/etc/docker/daemon.json`:

```json
{
    "runtimes": {
        "nvidia": {
            "path": "nvidia-container-runtime",
            "runtimeArgs": []
        },
        "runsc": {
            "path": "/usr/local/bin/runsc",
	    "runtimeArgs": ["--nvproxy", "--nvproxy-docker", "-debug-log=/tmp/runsc/", "-debug", "-strace"]

        }
    }
}
```

then run `sudo systemctl reload docker` 

To produce the error it suffices to just run the Official `text-embeddings-inference` Docker container image.

```
sudo docker run -it --gpus all --runtime runsc  --entrypoint bash ghcr.io/huggingface/text-embeddings-inference:0.3.0
```

On Gvisor this fails:

```
2023-10-30T18:42:48.005286Z  INFO text_embeddings_router: router/src/main.rs:152: Args { model_id: "the*****/***-*ase", revision: None, tokenization_workers: None, dtype: None, pooling: None, max_concurrent_requests: 512, max_batch_tokens: 16384, max_batch_requests: None, max_client_batch_size: 32, hf_api_token: None, hostname: "0b2d3becefc2", port: 80, uds_path: "/tmp/text-embeddings-inference-server", huggingface_hub_cache: Some("/data"), json_output: false, otlp_endpoint: None, cors_allow_origin: None }
2023-10-30T18:42:48.005739Z  INFO hf_hub: /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hf-hub-0.3.2/src/lib.rs:55: Token file not found "/root/.cache/huggingface/token"
2023-10-30T18:42:48.157136Z  INFO download_artifacts: text_embeddings_core::download: core/src/download.rs:9: Starting download
2023-10-30T18:42:48.157769Z  INFO download_artifacts: text_embeddings_core::download: core/src/download.rs:25: Model artifacts downloaded in 634.378µs
2023-10-30T18:42:48.177115Z  INFO text_embeddings_core::tokenization: core/src/tokenization.rs:22: Starting 8 tokenization workers
2023-10-30T18:42:48.256282Z  INFO text_embeddings_router: router/src/main.rs:251: Starting model backend
thread 'main' panicked at /root/.cargo/git/checkouts/cudarc-a08d71fd9258e74e/8be6ff4/src/driver/safe/core.rs:51:24:
called `Result::unwrap()` on an `Err` value: DriverError(CUDA_ERROR_OPERATING_SYSTEM, "OS call failed or operation not supported on this OS")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted
```

Running with `runc` the application proceeds past this point and with a T4 GPU fails with:

```
Caused by:
    Could not start backend: Runtime compute cap 75 is not compatible with compile time compute cap 80
```

But this can be fixed by using an A10G GPU. 

### runsc version

```shell
runsc version release-20231023.0-34-g83f75082e5b0
spec: 1.1.0-rc.1
```

### docker version (if using docker)

```shell
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:09:13 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:07:45 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.24
  GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc:
  Version:          1.1.9
  GitCommit:        v1.1.9-0-gccaecfc
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### uname

`Linux eef443dff72e 5.15.0-101.103.2.1.el9uek.x86_64 #2 SMP Tue May 2 01:10:45 PDT 2023 x86_64 x86_64 x86_64 GNU/Linux`

### runsc debug logs (if available)

```shell
This is just the relevant snippet of the boot logs: 


I1029 21:43:59.148759  779709 strace.go:605] [   5:   5] text-embeddings X ioctl(0x9 /dev/nvidiactl, 0xc020462b, 0x7eb13b39e1c0) = 0 (0x0) (50.251µs)
I1029 21:43:59.148798  779709 strace.go:567] [   5:   5] text-embeddings E ioctl(0x9 /dev/nvidiactl, 0xc020462a, 0x7eb13b39d750)
D1029 21:43:59.148805  779709 frontend.go:148] [   5:   5] nvproxy: frontend ioctl: nr = 0x0000002a, argSize = 0x00000020
D1029 21:43:59.148815  779709 frontend.go:482] [   5:   5] nvproxy: control command 0xd04
I1029 21:43:59.148836  779709 strace.go:605] [   5:   5] text-embeddings X ioctl(0x9 /dev/nvidiactl, 0xc020462a, 0x7eb13b39d750) = 0 (0x0) (29.95µs)
I1029 21:43:59.148871  779709 strace.go:567] [   5:   5] text-embeddings E ioctl(0x9 /dev/nvidiactl, 0xc020462a, 0x7eb13b39d750)
D1029 21:43:59.148877  779709 frontend.go:148] [   5:   5] nvproxy: frontend ioctl: nr = 0x0000002a, argSize = 0x00000020
D1029 21:43:59.148886  779709 frontend.go:482] [   5:   5] nvproxy: control command 0xd04
I1029 21:43:59.148899  779709 strace.go:605] [   5:   5] text-embeddings X ioctl(0x9 /dev/nvidiactl, 0xc020462a, 0x7eb13b39d750) = 0 (0x0) (21.11µs)
I1029 21:43:59.148929  779709 strace.go:567] [   5:   5] text-embeddings E ioctl(0x9 /dev/nvidiactl, 0xc028462b, 0x7eb13b39e140)
D1029 21:43:59.148936  779709 frontend.go:148] [   5:   5] nvproxy: frontend ioctl: nr = 0x0000002b, argSize = 0x00000028
D1029 21:43:59.148946  779709 frontend.go:638] [   5:   5] nvproxy: allocation class 0x0000cb33
W1029 21:43:59.148953  779709 frontend.go:650] [   5:   5] nvproxy: unknown allocation class 0x0000cb33
I1029 21:43:59.148960  779709 strace.go:605] [   5:   5] text-embeddings X ioctl(0x9 /dev/nvidiactl, 0xc028462b, 0x7eb13b39e140) = 0 (0x0) errno=22 (invalid argument) (22.5µs)
I1029 21:43:59.148993  779709 strace.go:567] [   5:   5] text-embeddings E ioctl(0x9 /dev/nvidiactl, 0xc0104629, 0x7eb13b39e130)
D1029 21:43:59.148999  779709 frontend.go:148] [   5:   5] nvproxy: frontend ioctl: nr = 0x00000029, argSize = 0x00000010
I1029 21:43:59.149165  779709 strace.go:605] [   5:   5] text-embeddings X ioctl(0x9 /dev/nvidiactl, 0xc0104629, 0x7eb13b39e130) = 0 (0x0) (153.282µs)
I1029 21:43:59.149243  779709 strace.go:561] [   5:   5] text-embeddings E close(0x9 /dev/nvidiactl)
I1029 21:43:59.149504  779709 strace.go:599] [   5:   5] text-embeddings X close(0x9 /dev/nvidiactl) = 0 (0x0) (12.76µs)
```

**Comment by ayushr2** [comment]
I can confirm that this is the same issue as https://github.com/google/gvisor/issues/9593. After patching @nixprime's commits, runsc also ends up with `Could not start backend: Runtime compute cap 75 is not compatible with compile time compute cap 80` on a T4 machine.

**Comment by ayushr2** [comment]
Hi @antony-frolov, sorry could you clarify if `ghcr.io/huggingface/text-embeddings-inference:turing-0.6` is **not** working with gVisor? But working on t4 (without gVisor) otherwise? If so, could you open a new bug with debug logs?

**Comment by antony-frolov** [comment]
Actually, i've just found you comment searching for the `Could not start backend: Runtime compute cap 75 is not compatible with compile time compute cap 80` error. I was trying to host bge-base-en-v1.5 and it turned out there was a special container to use with T5 tagged with `turing-0.x`.
